package com.marky.strivefit.ui.navigation

import kotlinx.serialization.Serializable

@Serializable object OnboardingGraph

@Serializable object Welcome
@Serializable object SignUp
@Serializable object Login
@Serializable object GuestLoading
@Serializable object PostAuthWelcome
@Serializable object root_router

@Serializable object MainAppGraph
@Serializable object UserSetupGraph

@Serializable object Home
@Serializable object Profile
@Serializable object Settings
@Serializable object Stats
@Serializable object Workout
@Serializable object WorkoutTracker
@Serializable object Challenges

@Serializable object UserSetupScreen1
@Serializable object UserSetupScreen2
@Serializable object UserSetupScreen3
@Serializable object UserSetupScreen4
@Serializable object UserSetupScreen5
@Serializable object UserSetupScreen6
@Serializable object UserSetupScreen7
@Serializable object UserSetupScreen8
@Serializable object UserSetupScreen9
@Serializable object UserSetupScreen10
@Serializable object UserSetupScreen11
@Serializable object UserSetupScreen12
@Serializable object UserSetupScreen13
@Serializable object UserSetupScreen14
@Serializable object UserSetupScreen15
@Serializable object UserSetupScreen16
@Serializable object UserSetupScreen17
@Serializable object UserSetupScreen18
@Serializable object UserSetupScreen19
@Serializable object UserSetupScreen20
@Serializable object UserSetupScreen21
@Serializable object UserSetupScreen22
@Serializable object UserSetupScreen23
@Serializable object UserSetupScreen24
@Serializable object UserSetupScreen25
@Serializable object UserSetupScreen26
@Serializable object UserSetupScreen27
@Serializable object UserSetupScreen28
@Serializable object UserSetupScreen29
@Serializable object UserSetupScreen30
@Serializable object UserSetupScreen31
@Serializable object UserSetupScreen32
@Serializable object UserSetupScreen33
@Serializable object UserSetupScreen34
@Serializable object UserSetupScreen35
@Serializable object UserSetupScreen36
@Serializable object UserSetupScreen37
@Serializable object UserSetupScreen38
@Serializable object UserSetupScreen39
@Serializable object UserSetupScreen40
@Serializable object UserSetupScreen41
@Serializable object UserSetupScreen42
@Serializable object UserSetupScreen43
@Serializable object UserSetupScreen44
@Serializable object UserSetupScreen45
@Serializable object UserSetupScreen46
@Serializable object UserSetupScreen47
@Serializable object UserSetupScreen48
@Serializable object UserSetupScreen49
@Serializable object UserSetupScreen50
@Serializable object UserSetupScreen51
@Serializable object UserSetupScreen52
@Serializable object UserSetupScreen53
@Serializable object UserSetupScreen54
@Serializable object UserSetupScreen55
@Serializable object UserSetupScreen56
@Serializable object UserSetupScreen57
@Serializable object UserSetupScreen58
@Serializable object UserSetupScreen59
@Serializable object UserSetupScreen60
@Serializable object UserSetupScreen61
@Serializable object UserSetupScreen62
@Serializable object UserSetupScreen63
@Serializable object UserSetupScreen64
@Serializable object UserSetupScreen65
@Serializable object UserSetupScreen66
@Serializable object UserSetupScreen67
@Serializable object UserSetupScreen68
@Serializable object UserSetupScreen69
@Serializable object UserSetupScreen70
@Serializable object UserSetupScreen71
@Serializable object UserSetupScreen72
@Serializable object UserSetupScreen73
@Serializable object UserSetupScreen74
@Serializable object UserSetupScreen75
@Serializable object UserSetupScreen76
@Serializable object UserSetupScreen77
@Serializable object UserSetupScreen78
@Serializable object UserSetupScreen79
@Serializable object UserSetupScreen80
@Serializable object UserSetupScreen81
@Serializable object UserSetupScreen82
@Serializable object UserSetupScreen83
@Serializable object UserSetupScreen84
@Serializable object UserSetupScreen85
@Serializable object UserSetupScreen86
@Serializable object UserSetupScreen87
@Serializable object UserSetupScreen88
@Serializable object UserSetupScreen89
@Serializable object UserSetupScreen90
@Serializable object UserSetupScreen91
@Serializable object UserSetupScreen92
@Serializable object UserSetupScreen93